<?php

/**
 * @file
 * SlickQuiz is a module to use jQuery plugin for creating dynamic quizzes.
 */

/**
 * Implements hook_node_info().
 */
function slickquiz_node_info() {
    return array(
      'squestion' => array(
          'name' => t('SlickQuiz Question'),
          'base' => 'node_content',
          'has_title' => TRUE,
          'title_label' => t('SlickQuiz Question Title'), 
          'description' => t('Create a question for SlickQuiz, accessible to users'),                   
      ),
      'squiz' => array(
          'name' => t('SlickQuiz'),
          'base' => 'node_content',
          'has_title' => TRUE,
          'title_label' => t('SlickQuiz Title'), 
          'description' => t('Create a SlickQuiz accessible to users'),                   
      )  
    );    
}